/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Component;
import java.beans.PropertyVetoException;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JFrame;
import java.text.DateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Ramon Santos
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        desktop = new javax.swing.JDesktopPane();
        LogoFrmPrincipal = new javax.swing.JLabel();
        lblUserfrmPrincipal = new javax.swing.JLabel();
        lblDatafrmPrincipal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        mnubarra = new javax.swing.JMenuBar();
        mnuArquivo = new javax.swing.JMenu();
        mnuArquivoConfiguracoes = new javax.swing.JMenuItem();
        mnuArquivoCUsuarios = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuArquivoSair = new javax.swing.JMenuItem();
        mnuMovimentos = new javax.swing.JMenu();
        mnuMovimentosVendas = new javax.swing.JMenuItem();
        mnuMovimentosCad = new javax.swing.JMenu();
        mnuMovimentosCadProd = new javax.swing.JMenuItem();
        mnuMovimentosCadClie = new javax.swing.JMenuItem();
        mnuMovimentosRel = new javax.swing.JMenu();
        mnuMovimentosRelVen = new javax.swing.JMenuItem();
        mnuMovimentosRelEst = new javax.swing.JMenuItem();
        mnuMovimentosRelES = new javax.swing.JMenuItem();
        mnuAjuda = new javax.swing.JMenu();
        mnuAjudaSobre = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONTROLE DE DOAÇÕES");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        desktop.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1111, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        LogoFrmPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LogoAtoDeAmor-removebg-preview.png"))); // NOI18N

        lblUserfrmPrincipal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUserfrmPrincipal.setText("Usuário");

        lblDatafrmPrincipal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDatafrmPrincipal.setText("Data");

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ramon Santos\\Downloads\\icons8-sair-24.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ramon Santos\\Downloads\\icons8-food-donor-24.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        mnuArquivo.setText("Arquivo");

        mnuArquivoConfiguracoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cog.png"))); // NOI18N
        mnuArquivoConfiguracoes.setText("Configurações");
        mnuArquivoConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArquivoConfiguracoesActionPerformed(evt);
            }
        });
        mnuArquivo.add(mnuArquivoConfiguracoes);

        mnuArquivoCUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuArquivoCUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/group.png"))); // NOI18N
        mnuArquivoCUsuarios.setText("Usuarios");
        mnuArquivoCUsuarios.setEnabled(false);
        mnuArquivoCUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArquivoCUsuariosActionPerformed(evt);
            }
        });
        mnuArquivo.add(mnuArquivoCUsuarios);
        mnuArquivo.add(jSeparator1);

        mnuArquivoSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuArquivoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/door_open.png"))); // NOI18N
        mnuArquivoSair.setText("Sair");
        mnuArquivoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArquivoSairActionPerformed(evt);
            }
        });
        mnuArquivo.add(mnuArquivoSair);

        mnubarra.add(mnuArquivo);

        mnuMovimentos.setText("Movimentos");

        mnuMovimentosVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        mnuMovimentosVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/box.png"))); // NOI18N
        mnuMovimentosVendas.setText("Estoque");
        mnuMovimentosVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMovimentosVendasActionPerformed(evt);
            }
        });
        mnuMovimentos.add(mnuMovimentosVendas);

        mnuMovimentosCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/application_form.png"))); // NOI18N
        mnuMovimentosCad.setText("Cadastros");

        mnuMovimentosCadProd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        mnuMovimentosCadProd.setText("Produtos");
        mnuMovimentosCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMovimentosCadProdActionPerformed(evt);
            }
        });
        mnuMovimentosCad.add(mnuMovimentosCadProd);

        mnuMovimentosCadClie.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        mnuMovimentosCadClie.setText("Doadores");
        mnuMovimentosCadClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMovimentosCadClieActionPerformed(evt);
            }
        });
        mnuMovimentosCad.add(mnuMovimentosCadClie);

        mnuMovimentos.add(mnuMovimentosCad);

        mnuMovimentosRel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/report.png"))); // NOI18N
        mnuMovimentosRel.setText("Relatorios");
        mnuMovimentosRel.setEnabled(false);

        mnuMovimentosRelVen.setText("Relatorio de doações");
        mnuMovimentosRelVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMovimentosRelVenActionPerformed(evt);
            }
        });
        mnuMovimentosRel.add(mnuMovimentosRelVen);

        mnuMovimentosRelEst.setText("Relatorio de estoques");
        mnuMovimentosRelEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMovimentosRelEstActionPerformed(evt);
            }
        });
        mnuMovimentosRel.add(mnuMovimentosRelEst);

        mnuMovimentosRelES.setText("Relatorio de Entrada/Saida ");
        mnuMovimentosRelES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMovimentosRelESActionPerformed(evt);
            }
        });
        mnuMovimentosRel.add(mnuMovimentosRelES);

        mnuMovimentos.add(mnuMovimentosRel);

        mnubarra.add(mnuMovimentos);

        mnuAjuda.setText("Ajuda");

        mnuAjudaSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuAjudaSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/information.png"))); // NOI18N
        mnuAjudaSobre.setText("Sobre");
        mnuAjudaSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAjudaSobreActionPerformed(evt);
            }
        });
        mnuAjuda.add(mnuAjudaSobre);

        mnubarra.add(mnuAjuda);

        setJMenuBar(mnubarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LogoFrmPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblDatafrmPrincipal))
                            .addComponent(lblUserfrmPrincipal))
                        .addGap(60, 60, 60)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 332, Short.MAX_VALUE)
                .addComponent(LogoFrmPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUserfrmPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDatafrmPrincipal)
                .addGap(14, 14, 14))
            .addComponent(desktop)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuMovimentosCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMovimentosCadProdActionPerformed
        // TODO add your handling code here:
        frmProduto Produto = new frmProduto();
        Produto.setVisible(true);
        desktop.add(Produto);
    }//GEN-LAST:event_mnuMovimentosCadProdActionPerformed

    private void mnuMovimentosRelVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMovimentosRelVenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuMovimentosRelVenActionPerformed

    private void mnuAjudaSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAjudaSobreActionPerformed
        //Chamando a tela sobre.
        frmSobre sobre = new frmSobre();
        sobre.setVisible(true);
    }//GEN-LAST:event_mnuAjudaSobreActionPerformed

    private void mnuMovimentosRelEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMovimentosRelEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuMovimentosRelEstActionPerformed

    private void mnuMovimentosCadClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMovimentosCadClieActionPerformed
        // chamando a tela doadores
        //frmCliente cliente = new frmDoadores();
        //cliente.setVisible(true);
        //desktop.add(cliente);
        frmDoadores cliente = new frmDoadores();
        desktop.add(cliente);
        cliente.show();
        try {
        cliente.setMaximum(true);
        
        }   
        catch (PropertyVetoException ex) {
        }
        
    }//GEN-LAST:event_mnuMovimentosCadClieActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // linhas abaixo servem para substiruir a data pela atual momento do login
        Date data = new Date ();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.MEDIUM);       
        lblDatafrmPrincipal.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void mnuMovimentosVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMovimentosVendasActionPerformed
        //as linhas abaixo irão abrir o form de vendas no desktop pane
        frmVenda mVenda = new frmVenda();
        mVenda.setVisible(true);
        desktop.add(mVenda);
    }//GEN-LAST:event_mnuMovimentosVendasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //BOTÃO SAIR
        int sair = JOptionPane.showConfirmDialog(null, "TEM CERTEZA QUE DESEJA SAIR?", "SAIR DO SISTEMA",JOptionPane.YES_NO_OPTION);
      if (sair == JOptionPane.YES_OPTION){
          System.exit(0);
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // BOTÃO PARA CADASTRO DE PRODUTO
        frmProduto Produto = new frmProduto();
        Produto.setVisible(true);
        desktop.add(Produto);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mnuArquivoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArquivoSairActionPerformed
        //exibe uma caixa para descidir se é isso mesmo
        int sair = JOptionPane.showConfirmDialog(null, "TEM CERTEZA QUE DESEJA SAIR?", "SAIR DO SISTEMA",JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_mnuArquivoSairActionPerformed

    private void mnuArquivoCUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArquivoCUsuariosActionPerformed
        //as linhas abaixo irão abrir o form de usuaris no desktop pane
        frmUsuarios mUsuario = new frmUsuarios();
        mUsuario.setVisible(true);
        desktop.add(mUsuario);
        //teste de atualização
    }//GEN-LAST:event_mnuArquivoCUsuariosActionPerformed

    private void mnuArquivoConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArquivoConfiguracoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuArquivoConfiguracoesActionPerformed

    private void mnuMovimentosRelESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMovimentosRelESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuMovimentosRelESActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoFrmPrincipal;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblDatafrmPrincipal;
    public static javax.swing.JLabel lblUserfrmPrincipal;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenuItem mnuAjudaSobre;
    private javax.swing.JMenu mnuArquivo;
    public static javax.swing.JMenuItem mnuArquivoCUsuarios;
    private javax.swing.JMenuItem mnuArquivoConfiguracoes;
    private javax.swing.JMenuItem mnuArquivoSair;
    private javax.swing.JMenu mnuMovimentos;
    private javax.swing.JMenu mnuMovimentosCad;
    private javax.swing.JMenuItem mnuMovimentosCadClie;
    private javax.swing.JMenuItem mnuMovimentosCadProd;
    public static javax.swing.JMenu mnuMovimentosRel;
    private javax.swing.JMenuItem mnuMovimentosRelES;
    private javax.swing.JMenuItem mnuMovimentosRelEst;
    private javax.swing.JMenuItem mnuMovimentosRelVen;
    private javax.swing.JMenuItem mnuMovimentosVendas;
    private javax.swing.JMenuBar mnubarra;
    // End of variables declaration//GEN-END:variables
}
