/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import java.sql.*;
import conexxao_BD.ModuloConexao;
import javax.swing.JOptionPane;
//import net.proteanit.sql.DbUtils;

public class frmVenda extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public frmVenda() {
        initComponents();
        conexao=ModuloConexao.conector();
    }
        private void pesquisar_cliente(){
//            String sql = "select NOME_CLIENTE as NOME from tbl_clientes where NOME_CLIENTE like ?";
//            
//            try {
//            //pasando o conteudo da caixa de pesquisa para o ?
//            pst = conexao.prepareStatement(sql);
//            pst.setString(1, txtCliVen.getText() + "%");
//            rs = pst.executeQuery();
//            // linha que serve para usar a biblioteca para preencher a tabela.
//            txtVendasTbl.setModel(DbUtils.resultSetToTableModel(rs));
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e);
//        }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome1 = new javax.swing.JLabel();
        txtCliId = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        txtCliEnd = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtCliNome = new javax.swing.JTextField();
        lblSenha2 = new javax.swing.JLabel();
        txtCliVen = new javax.swing.JTextField();
        lblSenha3 = new javax.swing.JLabel();
        txtCliEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtVendasTbl = new javax.swing.JTable();
        lblPerfil = new javax.swing.JLabel();
        txtUserPerfil = new javax.swing.JComboBox<>();
        lblSenha4 = new javax.swing.JLabel();
        txtCliEmail1 = new javax.swing.JTextField();
        btnAdicionarCli = new javax.swing.JButton();
        btnAlterarCli = new javax.swing.JButton();
        btnExcluirCli = new javax.swing.JButton();
        btnExcluirCli1 = new javax.swing.JButton();
        btnAdicionarCli1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtVendasTbl1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("VENDA");
        setPreferredSize(new java.awt.Dimension(1105, 700));

        lblNome1.setText("COD_VENDA");

        txtCliId.setEditable(false);
        txtCliId.setEnabled(false);

        lblSenha.setText("FUNCIONARIO");

        lblNome.setText("DATA");

        txtCliNome.setEditable(false);

        lblSenha2.setText("CLIENTE");

        txtCliVen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCliVenKeyReleased(evt);
            }
        });

        lblSenha3.setText("PRODUTOS");

        txtVendasTbl = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        txtVendasTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null}
            },
            new String [] {
                "CLIENTE"
            }
        ));
        txtVendasTbl.setFocusable(false);
        txtVendasTbl.getTableHeader().setReorderingAllowed(false);
        txtVendasTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtVendasTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(txtVendasTbl);

        lblPerfil.setText("FORMAS DE PAGAMENTO");

        txtUserPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "CREDITO", "DEBITO", "PIX", "DINHEIRO" }));
        txtUserPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserPerfilActionPerformed(evt);
            }
        });

        lblSenha4.setText("TOTAL VENDA");

        btnAdicionarCli.setText("FINALIZAR");
        btnAdicionarCli.setToolTipText("FINALIAR VENDA");
        btnAdicionarCli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdicionarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarCliActionPerformed(evt);
            }
        });

        btnAlterarCli.setText("ALTERAR");
        btnAlterarCli.setToolTipText("ALTERA ITEM DA VENDA");
        btnAlterarCli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarCliActionPerformed(evt);
            }
        });

        btnExcluirCli.setText("IMPRIMIR");
        btnExcluirCli.setToolTipText("IMPRIMIR COMPROVANTE");
        btnExcluirCli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluirCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCliActionPerformed(evt);
            }
        });

        btnExcluirCli1.setText("CANCELAR");
        btnExcluirCli1.setToolTipText("CANCELAR A VENDA ");
        btnExcluirCli1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluirCli1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCli1ActionPerformed(evt);
            }
        });

        btnAdicionarCli1.setText("ADICIONAR");
        btnAdicionarCli1.setToolTipText("ADICIONAR NOVO CLIENTE");
        btnAdicionarCli1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdicionarCli1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarCli1ActionPerformed(evt);
            }
        });

        txtVendasTbl = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        txtVendasTbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "QUANTIDADE", "PRODUTOS", "VALOR UNITARIO"
            }
        ));
        txtVendasTbl1.setFocusable(false);
        txtVendasTbl1.getTableHeader().setReorderingAllowed(false);
        txtVendasTbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtVendasTbl1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(txtVendasTbl1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSenha)
                            .addComponent(lblSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSenha3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(txtCliEmail)
                                    .addComponent(txtCliVen, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCliEnd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                                .addGap(51, 51, 51)
                                .addComponent(btnAdicionarCli1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCliId, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCliNome))
                                .addGap(150, 150, 150)
                                .addComponent(lblPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUserPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(lblSenha4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCliEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(btnAdicionarCli)
                        .addGap(41, 41, 41)
                        .addComponent(btnAlterarCli)
                        .addGap(51, 51, 51)
                        .addComponent(btnExcluirCli1)
                        .addGap(47, 47, 47)
                        .addComponent(btnExcluirCli)))
                .addGap(299, 299, 299))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(120, 120, 120)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(289, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(lblNome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblPerfil)
                            .addComponent(txtUserPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCliId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome1))
                        .addGap(18, 18, 18)
                        .addComponent(txtCliNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCliEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSenha))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtCliVen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblSenha2)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSenha3)
                        .addComponent(btnAdicionarCli1))
                    .addComponent(txtCliEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(217, 217, 217)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha4)
                    .addComponent(txtCliEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAlterarCli)
                        .addComponent(btnExcluirCli)
                        .addComponent(btnExcluirCli1))
                    .addComponent(btnAdicionarCli))
                .addGap(28, 28, 28))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(324, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(191, 191, 191)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtVendasTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtVendasTblMouseClicked
        // chamando o metodo setar campos
        //setar_campos();
    }//GEN-LAST:event_txtVendasTblMouseClicked

    private void txtUserPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserPerfilActionPerformed

    private void btnAdicionarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarCliActionPerformed
        // Chamando o metodo adicionar
        // adicionar();
    }//GEN-LAST:event_btnAdicionarCliActionPerformed

    private void btnAlterarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarCliActionPerformed
        // Chamando o metodo alterar
        //alterar();
    }//GEN-LAST:event_btnAlterarCliActionPerformed

    private void btnExcluirCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCliActionPerformed
        // Chamando o metodo remover
        //remover();
    }//GEN-LAST:event_btnExcluirCliActionPerformed

    private void btnExcluirCli1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCli1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirCli1ActionPerformed

    private void btnAdicionarCli1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarCli1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdicionarCli1ActionPerformed

    private void txtVendasTbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtVendasTbl1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVendasTbl1MouseClicked

    private void txtCliVenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCliVenKeyReleased
        // Chamando metodo pesquisar clientes
        pesquisar_cliente();
    }//GEN-LAST:event_txtCliVenKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarCli;
    private javax.swing.JButton btnAdicionarCli1;
    private javax.swing.JButton btnAlterarCli;
    private javax.swing.JButton btnExcluirCli;
    private javax.swing.JButton btnExcluirCli1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSenha2;
    private javax.swing.JLabel lblSenha3;
    private javax.swing.JLabel lblSenha4;
    private javax.swing.JTextField txtCliEmail;
    private javax.swing.JTextField txtCliEmail1;
    private javax.swing.JTextField txtCliEnd;
    private javax.swing.JTextField txtCliId;
    private javax.swing.JTextField txtCliNome;
    private javax.swing.JTextField txtCliVen;
    private javax.swing.JComboBox<String> txtUserPerfil;
    private javax.swing.JTable txtVendasTbl;
    private javax.swing.JTable txtVendasTbl1;
    // End of variables declaration//GEN-END:variables

}
